# Generated by Django 4.2.2 on 2023-11-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.CharField(choices=[('SEDENTARY', 'SEDENTARY'), ('LIGHTLY_ACTIVE', 'LIGHTLY_ACTIVE'), ('MODERATELY_ACTIVE', 'MODERATELY_ACTIVE'), ('VERY_ACTIVE', 'VERY_ACTIVE'), ('EXTREMELY_ACTIVE', 'EXTREMELY_ACTIVE')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='day_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('MALE', 'NAME'), ('FENAME', 'FENAME')], max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tdee',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.IntegerField(null=True),
        ),
    ]
