# Generated by Django 4.2.2 on 2023-11-29 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_alter_intructionstep_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='orgin',
            new_name='original',
        ),
    ]
