# Generated by Django 4.2.2 on 2023-11-29 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_rename_orgin_ingredient_original'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nutrient',
            old_name='percentOFdailyNeeds',
            new_name='percentOfDailyNeeds',
        ),
    ]
