# Generated by Django 4.2.2 on 2023-11-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_rename_percentofdailyneeds_nutrient_percentofdailyneeds'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='avg_rating',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='food',
            name='time_taken',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
    ]
