# Generated by Django 4.2.2 on 2023-11-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_food_avg_rating_food_time_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='caloies',
            field=models.FloatField(default=500),
        ),
    ]
