# Generated by Django 4.2.2 on 2023-11-29 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_food_caloies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='caloies',
            new_name='calories',
        ),
    ]
