# Generated by Django 4.2.2 on 2023-11-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_rename_caloies_food_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.IntegerField(default=500),
        ),
    ]
