# Generated by Django 4.2.2 on 2023-11-30 04:58

import base.custom_middleware
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_foodfeedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('favorite_food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritefood',
            name='user',
            field=models.ForeignKey(default=base.custom_middleware.get_current_user, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_foods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='favoritefood',
            unique_together={('user', 'food')},
        ),
    ]
